### ISSUE TITLE
öneri

### ISSUE THREAD

**Issue by ademilter** [scriptype/fermentemutfagim-static#1]
gatsbyjs veya nextjs kullan geç diyorum :)

**Comment by scriptype** [comment]
İlgi için sağ ol ama aslında sadece github pages'e deploy olsun diye göstermelik koydum buraya. Sitenin kendisinde şu an benzer bi tasarım implemente edilmiş, onunla kıyaslanabilsin diye kendi yaptığım bitmemiş versiyonu buraya koydum ben de.

edit:
https://enes.in/fermentemutfagim-static/ adresinden bu repoda bulunan bitmemiş versiyona bakabilirsin istersen.
